FROM alpine:3

# Install stuff necessary for Shell Adventure
RUN apk add --no-cache python3 py3-pip
RUN python3 -m pip --no-cache-dir install dill python-lorem

# The student will be user "bob"
RUN adduser -D bob
USER bob
WORKDIR /home/bob

CMD ["sh"]
