# The student will be user "student" and their password will be "student"
FROM alpine:3

# Install stuff
RUN apk add --no-cache python3 py3-pip

# Make new user and allow them to use sudo
RUN adduser -D student
USER student
WORKDIR /home/student

CMD ["sh"]
